// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXfOaZYbZZtJzxmKItmuaRfkqsHOYF5EI',
    appId: '1:108703758359:web:908527325fa27040b6c452',
    messagingSenderId: '108703758359',
    projectId: 'travelitineraryplanner-8411f',
    authDomain: 'travelitineraryplanner-8411f.firebaseapp.com',
    storageBucket: 'travelitineraryplanner-8411f.firebasestorage.app',
    measurementId: 'G-WR2GLQPWK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKqAJc5BDc3i8P4iQV4xzrGmOKg5Q7RBM',
    appId: '1:108703758359:android:3144dc05e207014eb6c452',
    messagingSenderId: '108703758359',
    projectId: 'travelitineraryplanner-8411f',
    storageBucket: 'travelitineraryplanner-8411f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVvKjL3GCBJjHuLG16t-7a0HGLgb99-dw',
    appId: '1:108703758359:ios:1157c0d840b34088b6c452',
    messagingSenderId: '108703758359',
    projectId: 'travelitineraryplanner-8411f',
    storageBucket: 'travelitineraryplanner-8411f.firebasestorage.app',
    iosBundleId: 'com.example.travelitineraryplanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVvKjL3GCBJjHuLG16t-7a0HGLgb99-dw',
    appId: '1:108703758359:ios:1157c0d840b34088b6c452',
    messagingSenderId: '108703758359',
    projectId: 'travelitineraryplanner-8411f',
    storageBucket: 'travelitineraryplanner-8411f.firebasestorage.app',
    iosBundleId: 'com.example.travelitineraryplanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXfOaZYbZZtJzxmKItmuaRfkqsHOYF5EI',
    appId: '1:108703758359:web:e25eebe924d9b5cdb6c452',
    messagingSenderId: '108703758359',
    projectId: 'travelitineraryplanner-8411f',
    authDomain: 'travelitineraryplanner-8411f.firebaseapp.com',
    storageBucket: 'travelitineraryplanner-8411f.firebasestorage.app',
    measurementId: 'G-VVXFH6S6GN',
  );

}